### ISSUE TITLE
VBET running error in cleaning outputs

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/RCAT#10]
@banderson1618 @bangen 
I have been running into errors with running VBET for the Lower John Day full network. I was originally running into this error...
![image](https://user-images.githubusercontent.com/30604787/46575937-715f5180-c97c-11e8-93c8-5d70dcc25d4d.png) Solved it!
but then I started from square one for the inputs and got the following error...
![image](https://user-images.githubusercontent.com/30604787/46576675-27329c00-c98d-11e8-8ed0-3e4cb8ec51d7.png)

Any ideas?

**Comment by bangen** [comment]
Made change from using reclassify function to con function (commit b58331e) which has resolved this issue.
