### ISSUE TITLE
VBET Project Builder Error

### ISSUE THREAD

**Issue by mhallerud** [Riverscapes/RCAT#13]
@jtgilbert I am continuously running into this error with the VBET Project Builder. It wasn't a huge deal when I was running at a watershed level since copying over files isn't that difficult, but now is inhibiting batch processing at larger scales. For troubleshooting, I have tried running on another machine with the same result and when I run the tool in ArcMap it freezes the program. There is also [this patch](https://support.esri.com/en/download/7653) available for this exact error, yet it does not seem to be doing anything after installing and restarting the computer. Any ideas?

![image](https://user-images.githubusercontent.com/43869036/55304261-d5347580-5407-11e9-80b5-378eff79c12a.png)

**Comment by bangen** [comment]
@mhallerud Was this resolved in the current batch code?

**Comment by mhallerud** [comment]
@bangen Yes, or at least I haven't seen it yet.

**Comment by bangen** [comment]
In that case I'm going to go ahead and close this issue for now.  We can re-open if the issue reoccurs.
