### ISSUE TITLE
Add banner

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RCAT#2]
@lhaycock , I made a [banner](https://github.com/Riverscapes/RCAT/blob/master/docs/assets/images/RCAT_Banner_Web.png) and [favicon](https://github.com/Riverscapes/RCAT/blob/master/docs/favicon.ico) posted with 3ce781d0d9f777be1d8daaddd07e1038a16b72d7. Please fix any path things I screwed up and add banner to all pages.

**Comment by lhaycock** [comment]
I have added it all the pages in R-CAT
