### ISSUE TITLE
RCAT Standards for Riverscapes Projects, Layer Packages & Symbology & 'Deliverables'

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RCAT#6]
After the Riparian Prioritization workshops, we started pulling together layer packages of RCAT projects. Micael has been doing a nice job of implementing these. A nice example is from the Big Wood on box: https://usu.box.com/s/dh63rs236a64f0oo3vigfz159c9r831x (see the layer packages).

I wanted to provide a little feedback (and at same time walk other users through whats in here).
See video:
https://youtu.be/mSq46i6Z0hk
The takehomes for Micael going forward:
## Layer Package
- This is looking good overall.
- Add the [USGSTopo WMTS](https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer) to the context layers `https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/WMTS/1.0.0/WMTSCapabilities.xml`
- Make most the raster layers transparent (30 to 40%) so they display nice with hillshades.
- Add to the context the wms you are using to make Atlas maps
- It would be nice to also export same contents as:
  - Layer Scene Package so you an open it in ArcGIS Earth
  - Load layer package onto our USU ArcGIS Online account.
## Deliverable PDF and PNG images
Careful that context map labels show up on top of watershed...
Please make the following as a matter of practice:
- A folder in `deliverables`, for different extents of the pretty maps you make. For here it would be `Big Wood`, and then `Rock Creek`.
- Within those different extent folders we should have:
  - A PDF atlas, with all Inputs, Outputs, Intermediates (with standard basemap - i.e. like you've done with hillshade in watershed and just the base )
![2018-05-10_114857](https://user-images.githubusercontent.com/9723905/39884769-29529220-5448-11e8-8a98-5af30d6aec2e.png)
  - A second PDF atlas, with all Inputs, Outputs, Intermediates with the USGSTopo as context.
  - A folder called `PNGs`  with PNG export individual maps of ALL the maps in the atlases, organized in exactly the same folder structure as the project. For example:
```
BigWood_RCAT (folder)
  - Outputs (folder)
    - RCA (folder)
      - 1704219_RCA.png
      - Intermediates (folder)
        - FloodplainAccessibility.png
        - LanduseIntensity.png
        - RVD.png
        - RVCT.png
  - Inputs (folder)
    - Valley Bottom (folder
       - Thiessen_Valley
       - 1704019_VBET_Edited.png
.... etc, etc. (see video)
```

**Comment by joewheaton** [comment]
@wally-mac  I assigned this to you for now. Please assign to Micael when he joins GitHub (I just sent him an invite).

**Comment by wally-mac** [comment]
@joewheaton This is great feedback.  Joe can you please also invite Chad chad.garlick@aggiemail.usu.edu to Joint GitHub? (Because you are the owner of this repository or please teach me how to do it).  Chad could help Mic get up to speed on the ArcGIS online functionality.

**Comment by joewheaton** [comment]
When I get back I will show you how...

**Comment by wally-mac** [comment]
I figured out how to Invite collaborators.

**Comment by wally-mac** [comment]
@chadFHC I assigned this to you for now but once Mic Albonico joins GitHub he'll take it over but you can help him get up to speed on the ArcGIS online functionality.

**Comment by Albonicomt** [comment]
Hey guys! I am on Github now.

**Comment by joewheaton** [comment]
Niceone @Albonicomt. Let us know if you have any questions or concerns on this...
