### ISSUE TITLE
Error message RVD

### ISSUE THREAD

**Issue by sshahverdian** [Riverscapes/RCAT#7]
@Albonicomt @MatthewMeier @bangen 
I could use some guidance running RCAT. I've been attempting to run RVD and so far with no luck.

The vegetation, valley bottom, and stream network data are here: 
https://usu.app.box.com/folder/51039831561

I have two problems: 1) RVD is taking just shy of forever to run - the last run was 22 hrs before cancelling (thanks to Matt - I made sure I am running everything on my machine, not from my external hard drive) and 2) I've gotten the same error message twice now - it says, "RVD tool aborted by user."

I've been using RCAT_1.0.11

Can someone try running these data? Also, how long does the RVD tool typically take to run?

**Comment by bangen** [comment]
I'm probably not the best for help on this since I've only run VBET.

**Comment by Albonicomt** [comment]
@sshahverdian, 22 hours is pretty gnarly... I am not sure what the issue is. I can give it a shot on my end. In my experience, an RVD run will take somewhere between 45 min to 4 hours depending on the type of data you are using. If you are using 10m data it can take 45min to an 1 hour 1/2 to run. If you are using higher resolution data it will definitely take longer. 

I will try running RVD on my end and see what happens and I will get back to you.

**Comment by sshahverdian** [comment]
@Albonicomt 
Thanks Mic. Let me know how it goes.

**Comment by Albonicomt** [comment]
@sshahverdian, I was able to successfully run the RVD tool. Although, it did take a little longer than usual at 5.5 hours. Not sure why that is the case... Here is a link to the RVD Project folder: https://usu.box.com/s/swb4b2ftykbnd0kky9mmr729i31el7a0

**Comment by sshahverdian** [comment]
Thanks Mic. Can you think of any reasons/anything you did that would have allowed you to run it with those inputs? I.e. did you perform and other pre-processing steps? I'm at a loss for why you would have been able to run it and I wouldn't. What version of RCAT and Arc did you use? I am experiencing similar troubles with BRAT (excessively long run time - at last count 10 hrs before I had to abort the BRAT table tool)...

**Comment by Albonicomt** [comment]
@sshahverdian , I am also at a loss... The only reason I can come up with is that it might be your computer, or maybe you kept running the tool off your external hard drive. I didn't do any extra processing steps at all. I just input the data you provided, as is. I ran the RCAT 1.0.11 version, which I believe is the latest version. 10 hours seems to be pretty excessive for BRAT, especially using 10m data. 
I wish I had more reason to why it is taking so long...

**Comment by bangen** [comment]
@sshahverdian It def should not be taking 10 hours to run the BRAT table tool.  Sounds like a computer issue to me.  Have you run BRAT on the same computer before?  Did you try running it on a different computer?

**Comment by sshahverdian** [comment]
@wally-mac I haven't finished it yet...BRAT is done and on Box. I have RVD and RVCT run - I need to finish RCAT.
